server:
  port: 7000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: item-server-route
        uri: lb://item-server
        predicates:
        - Path=/api/item/**
        filters:
        - StripPrefix=1
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka